-- Generated from lib/data/flowers.mock.ts — do not hand-edit, regenerate instead.

insert into public.flowers
  (id, bucket_no, common_name, latin_name, group_no, group_label, stage, days_planted, sow_method, sun_needs, watering_rule, expected_germination_days, disease_risk, note)
values
  ('african-marigold', 1, 'African Marigold', 'Tagetes erecta', 1, 'Direct Sow — Thriving', 'Flowering', 40, 'Direct sow into bed', 'Full sun', 'Keep soil evenly moist; ease off once flowering to avoid rot.', '5-7 days', 'Root rot in waterlogged soil', 'First bucket to flower this season — heavy bud set, deadhead weekly to keep it going.'),
  ('balsam', 2, 'Balsam', 'Impatiens balsamina', 1, 'Direct Sow — Thriving', 'Vegetative', 34, 'Direct sow into bed', 'Full sun to partial shade', 'Water daily in dry spells; balsam wilts fast when it dries out.', '7-10 days', 'Damping off at seedling stage', 'Thinned to 25cm spacing, bushing out nicely.'),
  ('cosmos', 3, 'Cosmos', 'Cosmos bipinnatus', 1, 'Direct Sow — Thriving', 'Budding', 30, 'Direct sow into bed', 'Full sun', 'Low water once established; drought-tolerant, avoid overwatering.', '7-10 days', 'Powdery mildew in humid weather', 'Tall and leggy already — may need a stake before the buds open.'),
  ('celosia', 4, 'Celosia', 'Celosia argentea', 1, 'Direct Sow — Thriving', 'Vegetative', 26, 'Direct sow into bed', 'Full sun', 'Moderate, consistent moisture — don''t let the bed go soggy.', '8-12 days', 'Leaf spot and root rot in poor drainage', 'Good even germination across the bucket.'),
  ('sunflower', 5, 'Sunflower', 'Helianthus annuus', 1, 'Direct Sow — Thriving', 'Budding', 32, 'Direct sow into bed', 'Full sun', 'Deep watering weekly; shallow watering encourages weak roots.', '7-10 days', 'Downy mildew; birds take seedlings early', 'Staked at day 18, now taller than the fence line.'),
  ('morning-glory', 6, 'Morning Glory', 'Ipomoea purpurea', 1, 'Direct Sow — Thriving', 'Vegetative', 28, 'Direct sow into bed (seeds soaked overnight)', 'Full sun', 'Moderate water; let the top soil dry between waterings.', '5-7 days (after soaking)', 'Fungal leaf spot in prolonged wet weather', 'Climbing the trellis fast, no flowers yet.'),
  ('cleome', 7, 'Cleome', 'Cleome hassleriana', 1, 'Direct Sow — Thriving', 'Seedling', 24, 'Direct sow into bed', 'Full sun', 'Moderate, even moisture while establishing.', '10-14 days', 'Generally resistant; watch for aphids', 'Slow starter but even germination across the bucket.'),
  ('marigold', 8, 'Marigold', 'Tagetes patula', 1, 'Direct Sow — Thriving', 'Seedling', 22, 'Direct sow into bed', 'Full sun', 'Keep evenly moist; avoid wetting foliage in the evening.', '5-7 days', 'Root rot; spider mites in dry spells', 'French marigold, compact habit — good border candidate.'),
  ('kochia', 9, 'Kochia', 'Bassia scoparia', 1, 'Direct Sow — Thriving', 'Germinated', 20, 'Direct sow into bed', 'Full sun', 'Low water once up; very drought-tolerant.', '10-15 days', 'Minimal; avoid standing water', 'Grown for the foliage hedge effect, not flowers.'),
  ('gaillardia', 10, 'Gaillardia', 'Gaillardia pulchella', 1, 'Direct Sow — Thriving', 'Germinated', 18, 'Direct sow into bed', 'Full sun', 'Low water; thrives on neglect once established.', '14-20 days', 'Powdery mildew and root rot in wet soil', 'Slowest of the direct-sow batch to come up, but on schedule.'),
  ('zinnia', 11, 'Zinnia', 'Zinnia elegans', 1, 'Direct Sow — Thriving', 'Vegetative', 26, 'Direct sow into bed', 'Full sun', 'Water at the base; wet foliage invites mildew.', '5-7 days', 'Powdery mildew', 'Best germination rate of the whole batch.'),
  ('salvia', 12, 'Salvia', 'Salvia splendens', 2, 'Started in Cups', 'Germinated', 16, 'Started in nursery cups', 'Full sun to partial shade', 'Keep cup mix consistently moist, never soggy.', '10-15 days', 'Damping off; watch for whitefly', 'Will transplant once it has two true leaf sets.'),
  ('verbena', 13, 'Verbena', 'Verbena x hybrida', 2, 'Started in Cups', 'Dormant', 14, 'Started in nursery cups', 'Full sun', 'Keep moist but not wet; verbena seed rots easily.', '14-21 days (slow, erratic)', 'Powdery mildew', 'Nothing up yet — verbena is notoriously slow and erratic, giving it the full 21 days before resowing.'),
  ('coreopsis', 14, 'Coreopsis', 'Coreopsis tinctoria', 2, 'Started in Cups', 'Germinated', 12, 'Started in nursery cups', 'Full sun', 'Low to moderate; let the surface dry between waterings.', '7-10 days', 'Generally pest-resistant', 'Quick and even germination across all cups.'),
  ('calliopsis', 15, 'Calliopsis', 'Coreopsis basalis', 2, 'Started in Cups', 'Germinated', 10, 'Started in nursery cups', 'Full sun', 'Low to moderate; avoid waterlogging the cups.', '7-10 days', 'Minimal', 'Cousin of coreopsis, tracking the same pace.'),
  ('gazania', 16, 'Gazania', 'Gazania rigens', 2, 'Started in Cups', 'Seedling', 18, 'Started in nursery cups', 'Full sun', 'Low water; sensitive to overwatering in cups.', '7-14 days', 'Root rot in overwatered mix', 'Pricked out to individual cups after first true leaves.'),
  ('kale', 17, 'Kale', 'Brassica oleracea', 2, 'Started in Cups', 'Vegetative', 14, 'Started in nursery cups', 'Full sun to partial shade', 'Consistent moisture; kale doesn''t like drying out.', '5-8 days', 'Aphids; clubroot in poorly drained mix', 'Fastest grower in the cup batch, ready to harden off soon.'),
  ('dahlia', 18, 'Dahlia', 'Dahlia pinnata', 3, 'Borderline', 'Seedling', 15, 'Direct sow, monitored closely', 'Full sun', 'Moderate water; keep the crown from sitting in water.', '5-7 days', 'Tuber/crown rot in waterlogged monsoon soil', 'Up and growing, but the bed drains slowly — watching for rot at the base.'),
  ('chrysanthemum', 19, 'Chrysanthemum', 'Chrysanthemum morifolium', 3, 'Borderline', 'Germinated', 13, 'Direct sow, monitored closely', 'Full sun to partial shade', 'Moderate water; ensure sharp drainage.', '10-15 days', 'Root rot in monsoon humidity', 'Just germinated, right at the edge of its normal window.'),
  ('dimorphotheca', 20, 'Dimorphotheca', 'Dimorphotheca sinuata', 3, 'Borderline', 'Seedling', 20, 'Direct sow, monitored closely', 'Full sun', 'Low water; hates wet feet, water only when topsoil is dry.', '10-14 days', 'Root rot in high humidity', 'Leaves yellowing slightly — likely excess moisture from monsoon rain.'),
  ('osteospermum', 21, 'Osteospermum', 'Osteospermum ecklonis', 3, 'Borderline', 'Germinated', 16, 'Direct sow, monitored closely', 'Full sun', 'Low to moderate; needs sharp drainage.', '10-14 days', 'Fungal rot in prolonged humidity', 'Similar risk profile to Dimorphotheca — watching closely.'),
  ('gypsophila', 22, 'Gypsophila', 'Gypsophila elegans', 3, 'Borderline', 'Dormant', 9, 'Direct sow, monitored closely', 'Full sun', 'Low water; well-drained soil is critical.', '10-15 days', 'Root rot in wet soil — high risk this season', 'Nothing visible yet, still inside its normal germination window.'),
  ('helichrysum', 23, 'Helichrysum', 'Helichrysum bracteatum', 3, 'Borderline', 'Germinated', 17, 'Direct sow, monitored closely', 'Full sun', 'Low water once established; drought-tolerant.', '10-14 days', 'Root rot in damp conditions', 'Came up later than expected but looks healthy.'),
  ('ice-plant', 24, 'Ice Plant', 'Delosperma cooperi', 3, 'Borderline', 'Dormant', 22, 'Direct sow, monitored closely', 'Full sun', 'Very low water; succulent-type, hates wet soil.', '14-21 days', 'Rot in monsoon humidity — highest risk in this bucket', 'No germination yet past the expected window; likely seed rot from humidity, considering a resow in a drier mix.'),
  ('petunia', 25, 'Petunia', 'Petunia x hybrida', 4, 'Wrong Season — Dormant', 'Dormant', 0, 'Hold — sow post-monsoon in cool season', 'Full sun', 'N/A — seed held, not yet sown.', '10-14 days (light-dependent)', 'Botrytis in high humidity', 'Cool-season annual; monsoon humidity would cause damping off and botrytis. Holding seed for the post-monsoon window.'),
  ('pansy', 26, 'Pansy', 'Viola x wittrockiana', 4, 'Wrong Season — Dormant', 'Dormant', 0, 'Hold — sow post-monsoon in cool season', 'Full sun to partial shade', 'N/A — seed held, not yet sown.', '10-20 days', 'Root rot in heat and humidity', 'Strictly a cool-season flower; heat and humidity now would rot seed before it sprouts.'),
  ('antirrhinum', 27, 'Antirrhinum', 'Antirrhinum majus', 4, 'Wrong Season — Dormant', 'Dormant', 0, 'Hold — sow post-monsoon in cool season', 'Full sun', 'N/A — seed held, not yet sown.', '10-14 days', 'Rust in humid weather', 'Snapdragon; rust pressure is too high in monsoon humidity, better sown in the cool season.'),
  ('dianthus', 28, 'Dianthus', 'Dianthus chinensis', 4, 'Wrong Season — Dormant', 'Dormant', 0, 'Hold — sow post-monsoon in cool season', 'Full sun', 'N/A — seed held, not yet sown.', '7-14 days', 'Fungal leaf spot in humidity', 'Prefers cooler, drier conditions than monsoon offers — held for later.'),
  ('calendula', 29, 'Calendula', 'Calendula officinalis', 4, 'Wrong Season — Dormant', 'Dormant', 0, 'Hold — sow post-monsoon in cool season', 'Full sun', 'N/A — seed held, not yet sown.', '7-14 days', 'Powdery mildew in warm, humid weather', 'Pot Marigold does best in cooler weather; monsoon heat and humidity invite mildew.'),
  ('delphinium', 30, 'Delphinium', 'Delphinium elatum', 4, 'Wrong Season — Dormant', 'Dormant', 0, 'Hold — sow post-monsoon in cool season', 'Full sun to partial shade', 'N/A — seed held, not yet sown.', '15-20 days', 'Powdery mildew and crown rot in humidity', 'Strongly cool-season; crown rot risk in monsoon soil is very high.'),
  ('hollyhock', 31, 'Hollyhock', 'Alcea rosea', 4, 'Wrong Season — Dormant', 'Dormant', 0, 'Hold — sow post-monsoon in cool season', 'Full sun', 'N/A — seed held, not yet sown.', '10-14 days', 'Rust — major risk in humid monsoon conditions', 'Rust pressure on hollyhock foliage is severe in monsoon humidity; better sown after the rains ease.'),
  ('nasturtium', 32, 'Nasturtium', 'Tropaeolum majus', 4, 'Wrong Season — Dormant', 'Dormant', 0, 'Hold — sow post-monsoon in cool season', 'Full sun', 'N/A — seed held, not yet sown.', '7-14 days', 'Seed rot in waterlogged monsoon soil', 'Prefers poor, well-drained soil — monsoon waterlogging would rot the seed before sprouting.'),
  ('alyssum', 33, 'Alyssum', 'Lobularia maritima', 4, 'Wrong Season — Dormant', 'Dormant', 0, 'Hold — sow post-monsoon in cool season', 'Full sun to partial shade', 'N/A — seed held, not yet sown.', '5-10 days', 'Damping off in wet, humid conditions', 'Sweet alyssum rots quickly in wet humid soil; holding for the cool, drier season.'),
  ('nemesia', 34, 'Nemesia', 'Nemesia strumosa', 4, 'Wrong Season — Dormant', 'Dormant', 0, 'Hold — sow post-monsoon in cool season', 'Full sun to partial shade', 'N/A — seed held, not yet sown.', '10-15 days', 'Root rot in heat and humidity', 'Struggles in heat and humidity; holding for a cooler sowing window.'),
  ('nemophila', 35, 'Nemophila', 'Nemophila menziesii', 4, 'Wrong Season — Dormant', 'Dormant', 0, 'Hold — sow post-monsoon in cool season', 'Partial shade', 'N/A — seed held, not yet sown.', '10-15 days', 'Root rot in monsoon humidity', 'Baby Blue Eyes dislikes heat as much as it dislikes wet feet — held for a cooler window.');

insert into public.events
  (flower_id, type, label, day_number, notes, to_stage, created_at)
values
  ('african-marigold', 'sown', 'Sown', 0, null, null, '2026-05-24T12:00:00Z'),
  ('african-marigold', 'germinated', 'Germinated', 6, null, null, '2026-05-30T12:00:00Z'),
  ('african-marigold', 'budding', 'First buds', 26, null, null, '2026-06-19T12:00:00Z'),
  ('african-marigold', 'bloomed', 'First bloom', 37, null, null, '2026-06-30T12:00:00Z'),
  ('balsam', 'sown', 'Sown', 0, null, null, '2026-05-30T12:00:00Z'),
  ('balsam', 'germinated', 'Germinated', 8, null, null, '2026-06-07T12:00:00Z'),
  ('balsam', 'thinned', 'Thinned to 25cm', 15, null, null, '2026-06-14T12:00:00Z'),
  ('cosmos', 'sown', 'Sown', 0, null, null, '2026-06-03T12:00:00Z'),
  ('cosmos', 'germinated', 'Germinated', 8, null, null, '2026-06-11T12:00:00Z'),
  ('cosmos', 'budding', 'First buds', 24, null, null, '2026-06-27T12:00:00Z'),
  ('cosmos', 'bloomed', 'Expected first bloom', 50, 'Predicted from typical cosmos bud-to-bloom timing.', null, '2026-07-23T12:00:00Z'),
  ('celosia', 'sown', 'Sown', 0, null, null, '2026-06-07T12:00:00Z'),
  ('celosia', 'germinated', 'Germinated', 10, null, null, '2026-06-17T12:00:00Z'),
  ('celosia', 'thinned', 'Thinned', 20, null, null, '2026-06-27T12:00:00Z'),
  ('sunflower', 'sown', 'Sown', 0, null, null, '2026-06-01T12:00:00Z'),
  ('sunflower', 'germinated', 'Germinated', 8, null, null, '2026-06-09T12:00:00Z'),
  ('sunflower', 'note', 'Staked', 18, 'Added support stake against monsoon wind.', null, '2026-06-19T12:00:00Z'),
  ('sunflower', 'budding', 'First bud', 28, null, null, '2026-06-29T12:00:00Z'),
  ('sunflower', 'bloomed', 'Expected first bloom', 40, 'Predicted bloom window for sunflower.', null, '2026-07-11T12:00:00Z'),
  ('morning-glory', 'sown', 'Sown (soaked seed)', 0, null, null, '2026-06-05T12:00:00Z'),
  ('morning-glory', 'germinated', 'Germinated', 6, null, null, '2026-06-11T12:00:00Z'),
  ('morning-glory', 'note', 'Trellised', 14, 'Trained vines onto trellis.', null, '2026-06-19T12:00:00Z'),
  ('cleome', 'sown', 'Sown', 0, null, null, '2026-06-09T12:00:00Z'),
  ('cleome', 'germinated', 'Germinated', 12, null, null, '2026-06-21T12:00:00Z'),
  ('cleome', 'thinned', 'Thinned', 20, null, null, '2026-06-29T12:00:00Z'),
  ('marigold', 'sown', 'Sown', 0, null, null, '2026-06-11T12:00:00Z'),
  ('marigold', 'germinated', 'Germinated', 6, null, null, '2026-06-17T12:00:00Z'),
  ('marigold', 'note', 'True leaves', 14, 'First true leaf set visible.', null, '2026-06-25T12:00:00Z'),
  ('kochia', 'sown', 'Sown', 0, null, null, '2026-06-13T12:00:00Z'),
  ('kochia', 'germinated', 'Germinated', 12, null, null, '2026-06-25T12:00:00Z'),
  ('gaillardia', 'sown', 'Sown', 0, null, null, '2026-06-15T12:00:00Z'),
  ('gaillardia', 'germinated', 'Germinated', 15, null, null, '2026-06-30T12:00:00Z'),
  ('zinnia', 'sown', 'Sown', 0, null, null, '2026-06-07T12:00:00Z'),
  ('zinnia', 'germinated', 'Germinated', 6, null, null, '2026-06-13T12:00:00Z'),
  ('zinnia', 'thinned', 'Thinned', 14, null, null, '2026-06-21T12:00:00Z'),
  ('salvia', 'sown', 'Sown in cups', 0, null, null, '2026-06-17T12:00:00Z'),
  ('salvia', 'germinated', 'Germinated', 12, null, null, '2026-06-29T12:00:00Z'),
  ('verbena', 'sown', 'Sown in cups', 0, null, null, '2026-06-19T12:00:00Z'),
  ('coreopsis', 'sown', 'Sown in cups', 0, null, null, '2026-06-21T12:00:00Z'),
  ('coreopsis', 'germinated', 'Germinated', 8, null, null, '2026-06-29T12:00:00Z'),
  ('calliopsis', 'sown', 'Sown in cups', 0, null, null, '2026-06-23T12:00:00Z'),
  ('calliopsis', 'germinated', 'Germinated', 8, null, null, '2026-07-01T12:00:00Z'),
  ('gazania', 'sown', 'Sown in cups', 0, null, null, '2026-06-15T12:00:00Z'),
  ('gazania', 'germinated', 'Germinated', 10, null, null, '2026-06-25T12:00:00Z'),
  ('gazania', 'note', 'Pricked out', 15, 'Moved to individual cups.', null, '2026-06-30T12:00:00Z'),
  ('kale', 'sown', 'Sown in cups', 0, null, null, '2026-06-19T12:00:00Z'),
  ('kale', 'germinated', 'Germinated', 6, null, null, '2026-06-25T12:00:00Z'),
  ('kale', 'note', 'True leaves', 10, 'First true leaves emerging.', null, '2026-06-29T12:00:00Z'),
  ('dahlia', 'sown', 'Sown', 0, null, null, '2026-06-18T12:00:00Z'),
  ('dahlia', 'germinated', 'Germinated', 6, null, null, '2026-06-24T12:00:00Z'),
  ('chrysanthemum', 'sown', 'Sown', 0, null, null, '2026-06-20T12:00:00Z'),
  ('chrysanthemum', 'germinated', 'Germinated', 12, null, null, '2026-07-02T12:00:00Z'),
  ('dimorphotheca', 'sown', 'Sown', 0, null, null, '2026-06-13T12:00:00Z'),
  ('dimorphotheca', 'germinated', 'Germinated', 12, null, null, '2026-06-25T12:00:00Z'),
  ('dimorphotheca', 'note', 'Yellowing leaves', 18, 'Possible excess moisture — eased back watering.', null, '2026-07-01T12:00:00Z'),
  ('osteospermum', 'sown', 'Sown', 0, null, null, '2026-06-17T12:00:00Z'),
  ('osteospermum', 'germinated', 'Germinated', 12, null, null, '2026-06-29T12:00:00Z'),
  ('gypsophila', 'sown', 'Sown', 0, null, null, '2026-06-24T12:00:00Z'),
  ('helichrysum', 'sown', 'Sown', 0, null, null, '2026-06-16T12:00:00Z'),
  ('helichrysum', 'germinated', 'Germinated', 12, null, null, '2026-06-28T12:00:00Z'),
  ('ice-plant', 'sown', 'Sown', 0, null, null, '2026-06-11T12:00:00Z'),
  ('ice-plant', 'note', 'No germination', 20, 'Past expected window — suspect rot from monsoon humidity.', null, '2026-07-01T12:00:00Z'),
  ('petunia', 'note', 'Held for post-monsoon sowing', 0, null, null, '2026-07-03T12:00:00Z'),
  ('pansy', 'note', 'Held for post-monsoon sowing', 0, null, null, '2026-07-03T12:00:00Z'),
  ('antirrhinum', 'note', 'Held for post-monsoon sowing', 0, null, null, '2026-07-03T12:00:00Z'),
  ('dianthus', 'note', 'Held for post-monsoon sowing', 0, null, null, '2026-07-03T12:00:00Z'),
  ('calendula', 'note', 'Held for post-monsoon sowing', 0, null, null, '2026-07-03T12:00:00Z'),
  ('delphinium', 'note', 'Held for post-monsoon sowing', 0, null, null, '2026-07-03T12:00:00Z'),
  ('hollyhock', 'note', 'Held for post-monsoon sowing', 0, null, null, '2026-07-03T12:00:00Z'),
  ('nasturtium', 'note', 'Held for post-monsoon sowing', 0, null, null, '2026-07-03T12:00:00Z'),
  ('alyssum', 'note', 'Held for post-monsoon sowing', 0, null, null, '2026-07-03T12:00:00Z'),
  ('nemesia', 'note', 'Held for post-monsoon sowing', 0, null, null, '2026-07-03T12:00:00Z'),
  ('nemophila', 'note', 'Held for post-monsoon sowing', 0, null, null, '2026-07-03T12:00:00Z');

